version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sehatsetu_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: EventAdmin1234
      POSTGRES_DB: sehatsetu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: sehatsetu_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sehatsetu.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: sehatsetu_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: sehatsetu_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
