"""Add health info table

Revision ID: 03c70f99ab68
Revises: 9104061470bc
Create Date: 2026-08-28 22:06:23.193642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c70f99ab68'
down_revision: Union[str, Sequence[str], None] = '9104061470bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_information',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('general_precautions', sa.String(), nullable=True),
    sa.Column('when_to_seek_care', sa.String(), nullable=True),
    sa.Column('emergency_warning_signs', sa.String(), nullable=True),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_information_category'), 'health_information', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_information_category'), table_name='health_information')
    op.drop_table('health_information')
    # ### end Alembic commands ###
