"""Add facility and doctor tables

Revision ID: 0700a2d6235d
Revises: 0b9ba2a8e259
Create Date: 2026-08-28 22:03:22.918605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0700a2d6235d'
down_revision: Union[str, Sequence[str], None] = '0b9ba2a8e259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcare_facilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pin_code', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('is_24_7', sa.Boolean(), nullable=True),
    sa.Column('has_emergency', sa.Boolean(), nullable=True),
    sa.Column('opening_hours', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthcare_facilities_district'), 'healthcare_facilities', ['district'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_name'), 'healthcare_facilities', ['name'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_type'), 'healthcare_facilities', ['type'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('doctors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('consultation_fee', sa.Float(), nullable=True),
    sa.Column('availability_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['healthcare_facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_name'), 'doctors', ['name'], unique=False)
    op.create_index(op.f('ix_doctors_specialization'), 'doctors', ['specialization'], unique=False)
    op.create_table('facility_services',
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['healthcare_facilities.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('facility_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility_services')
    op.drop_index(op.f('ix_doctors_specialization'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_name'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_healthcare_facilities_type'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_name'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_district'), table_name='healthcare_facilities')
    op.drop_table('healthcare_facilities')
    # ### end Alembic commands ###
