"""add_escalation_fields_to_appointments

Revision ID: 136fa8ac3fb9
Revises: e9a776731037
Create Date: 2026-08-29 11:25:07.896770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136fa8ac3fb9'
down_revision: Union[str, Sequence[str], None] = 'e9a776731037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('is_escalated', sa.Boolean(), nullable=True))
    op.add_column('appointments', sa.Column('urgency_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'urgency_level')
    op.drop_column('appointments', 'is_escalated')
    # ### end Alembic commands ###
