"""Add hospital dashboard fields

Revision ID: e9a776731037
Revises: cfbc946eb982
Create Date: 2026-08-28 23:06:17.941605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a776731037'
down_revision: Union[str, Sequence[str], None] = 'cfbc946eb982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('decline_reason', sa.String(), nullable=True))
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('appointments_service_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'is_callback_request')
    op.drop_column('appointments', 'service_id')
    op.add_column('users', sa.Column('managed_facility_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'healthcare_facilities', ['managed_facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'managed_facility_id')
    op.add_column('appointments', sa.Column('service_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('is_callback_request', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('appointments_service_id_fkey'), 'appointments', 'services', ['service_id'], ['id'])
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('appointments', 'decline_reason')
    # ### end Alembic commands ###
